### ISSUE TITLE
Application 'condition-survey' died in status LOADING_SOURCE_CODE: "does not export an unmount function or array of functions"

### ISSUE THREAD

**Issue by Vshri** [joeldenning/coexisting-angular-microfrontends#14] opened 2019-08-28 14:21 UTC
Hi,

I am newbie and this is my first angular project.

I am implementing micro front ends with existing two angular 7 projects and navbar so that when I click on particular router-link it should redirect to that project. To do this I have installed single spa(^3.0.1) and created extra-webpack.config.js in /ConditionSurveyDemo and main.single-spa.ts in /ConditionSurveyDemo/src (ConditionSurveyDemo is my existing project) and it is running succesfully. But when i click on conditionSurvey router-link i am getting this error

![image](https://user-images.githubusercontent.com/29140905/63864213-18057400-c9cd-11e9-82d5-65f8f425ce37.png)

Below is my main.single-spa.ts file

![image](https://user-images.githubusercontent.com/29140905/63863221-7893b180-c9cb-11e9-89ed-567140fbc114.png)

am I missing anything? Can you please help me.

Thanks!!

**Comment by Vshri** [comment] 2019-08-29 14:23
Hi thanks for your reply.

Tried both using angular builder and by updating angular 7 to angular 8.  Now i am getting one more issue with existing issue as below

![image](https://user-images.githubusercontent.com/29140905/63947547-bdcfe600-ca94-11e9-86c7-14565aa5d478.png)

I have bootstrapped AppComponent in AppModule and have 'app-root' in my index page.

**Comment by joeldenning** [comment] 2019-08-29 15:00
`app-root` needs to match exactly the component selector for your `app.component.ts` file. See [example](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/app1/src/app/app.component.ts) and [docs](https://single-spa.js.org/docs/ecosystem-angular.html#installation). In the docs I linked to, notice the info about `--prefix`.

Regarding `does not export an unmount function or array of functions` -- try going through the interactive walkthrough on http://single-spa-playground.org. It will diagnose that error and help you fix it.

**Comment by Vshri** [comment] 2019-09-04 14:30
Hi, Thanks for reference links. I have gone through link and followed same steps to create apps. But I am getting error 
![image](https://user-images.githubusercontent.com/29140905/64263666-a5a50e80-cf4d-11e9-9400-2f7e7607cbe3.png)

I have been checking to fix this error, but no luck. You can also find attached zip folder of my project for more information.

[TestSPA.zip](https://github.com/joeldenning/coexisting-angular-microfrontends/files/3574968/TestSPA.zip)

Thanks!!

**Comment by Vshri** [comment] 2019-09-06 08:53
Hi, Thanks for your reply.

Suggested documents really helped me. I have successfully created application as suggested by you. However I managed to resolve some errors. But now I am facing error in routing when i click on application 1 
![image](https://user-images.githubusercontent.com/29140905/64412860-faf83180-d0ad-11e9-8930-f0c30347325f.png)

I have followed https://github.com/CanopyTax/single-spa-angular/issues/65#issuecomment-488794942 to resolve but no luck. 

 you can find attached working TestSPA project folder for more info.
[TestSPA.zip](https://github.com/joeldenning/coexisting-angular-microfrontends/files/3583081/TestSPA.zip)

**Comment by joeldenning** [comment] 2019-09-07 22:10
I took a look at your zipped code. You should not specify the APP_BASE_HREF as `condition-survey`, but instead as `/`. Then your routes need to each specify `condition-survey`. See related https://single-spa.js.org/docs/ecosystem-angular.html#configure-routes.

Closing this issue since it's not a bug with single-spa or coexisting-angular-microfrontends. But feel free to keep commenting here for further discussion.

**Closed by joeldenning** 2019-09-07 22:10 UTC
