### ISSUE TITLE
Infinite router redirect loop 

### ISSUE THREAD

**Issue by MykolaShevchuk** [joeldenning/coexisting-angular-microfrontends#5] opened 2019-07-02 15:29 UTC
I've noticed one critical issue with a router in "coexisting-angular-microfrontends" project:

When I switch quickly from app1 to app2 and switch back to app1  before app2 was completely loaded and rendered I'm getting into an infinite redirect loop.

Here is a demo: 
![](https://media.giphy.com/media/TfRNYxij523bpXvOrH/giphy.gif)

Could you suggest anything? 
Thank you!

**Comment by joeldenning** [comment] 2019-07-05 00:13
Hey @MykolaShevchuk, I have seen issues sort of similar to this but have struggled to replicate the issue. I just tried this again on coexisting-angular-microfrontends.surge.sh, but was unable to see the problem.

Any tips on how to get this to happen consistently? I would definitely like to fix the problem.

**Comment by MykolaShevchuk** [comment] 2019-07-05 10:10
Thank you @joeldenning. I can reproduce it on http://coexisting-angular-microfrontends.surge.sh

**Steps to reproduce:**
1. Open http://coexisting-angular-microfrontends.surge.sh/ and with not loaded "App 1"
2. Click "App 1"
3. Click "Home". 
4. And here is happening something strange:
If you had clicked "Home" after "App1" was fully loaded - everything is fine;
if you had clicked  "Home" very very fast - everything is fine;
if you had clicked  "Home" after small delay like 500ms - it starts redirect loop between '/' and '/app1'.

**Comment by joeldenning** [comment] 2019-07-06 16:31
I was able to replicate this error only one time after about 20 attempts. Afterwards, I upgraded all of the single-spa applications in this repo to Angular 8.

Could you verify if you can still replicate the error, now that everything is upgraded to Angular 8? I think I don't know the click timing as well as you do 😄

**Comment by nashvillenarayan** [comment] 2019-07-06 22:28
Hello Joeldenning,
We are also facing the same issue . we are using five applications which are built on Angular-7.2.  It is happening sporadically , i feel it is not issue with click timing or delay of loading.

**Comment by joeldenning** [comment] 2019-07-06 22:29
@nashvillenarayan any information that you could provide that would help me replicate this issue reliably would be appreciated.

**Comment by MykolaShevchuk** [comment] 2019-07-08 12:30
@joeldenning I've just tested updated version with angular8. Unfortunately, it's still reproducible.

**Comment by joeldenning** [comment] 2019-07-08 18:30
Hmm I will try to find some time to figure out how to make this consistent to reproduce.

**Comment by joeldenning** [comment] 2019-07-18 17:01
I just tried to recreate the problem and was unable to do so. Until there is a way to consistently demonstrate the problem, I will be unable to fix it.

**Comment by ywager** [comment] 2019-07-30 12:17
Hi Joeldenning,
I also encountered this problem, using angular7.
I have uploaded my code to github(https://github.com/ywager/angular-microfrontends), and the steps and problems have been described in the project README. If you are comfortable, you can test it.

**Comment by joeldenning** [comment] 2019-07-30 15:54
👍 I'll check it out the next time I get a chance.

**Comment by joeldenning** [comment] 2019-08-01 16:07
This might be related too <img width="864" alt="image" src="https://user-images.githubusercontent.com/5524384/62309086-fc499500-b443-11e9-8cfe-7653664f7c12.png">

https://github.com/korjikk/angular-single-spa-routing-issue

**Comment by AndrewGlazier** [comment] 2019-10-30 13:49
Hi @joeldenning, I'm also experiencing this issue;

Things I've found which assist with reproduction:
IE11 reproduces this issue more consistently
Making the button swap on click so you can simply double click makes the timing more easily replicable

**Comment by AndrewGlazier** [comment] 2019-10-31 10:05
Have opened this ticket with more details:
https://github.com/CanopyTax/single-spa-angular/issues/113

**Comment by joeldenning** [comment] 2019-10-31 18:07
I do not have time to work on this issue. In the past I've spent >30 hours trying to get Angular Router and ZoneJS to not behave weirdly. The root cause of the bug is that ZoneJS monkey patches all of the native browser functions and makes assumptions about who is calling those functions (and when) that do not hold true with single-spa. I have little interest in attempting to work on this issue again in the near future, since I'm swamped with other work and this bug is a frustrating one I've already lost a lot of time to.

I would gladly accept a PR from the community to fix this. Since we now have https://github.com/CanopyTax/single-spa-angular/issues/113, I'm going to close this issue in favor of that one.

**Closed by joeldenning** 2019-10-31 18:07 UTC
