### ISSUE TITLE
Unable to include third party libraries with  "single-spa-angular"

### ISSUE THREAD

**Issue by nashvillenarayan** [joeldenning/coexisting-angular-microfrontends#4] opened 2019-06-21 12:40 UTC
Hello ,
We have developed portal which had 5 angular @7 projects , which are all running in @7.3.6 cli version with  single-spa-sngular: "^3.0.0-beta.20" . All our applications are using different third party packages like echarts, deepstream ..etc.  We are getting error as object undefined even though the scripts are loaded correctly. 
 We updated the required scripts in the angular.cli at architect/build  Scripts   "scripts": [ 
              "./node_modules/deepstream.io-client-js/dist/deepstream.js",
              "./node_modules/echarts/dist/echarts.min.js"]

Can you help us if we are missing any step. 
Thank you.

**Comment by joeldenning** [comment] 2019-06-21 13:36
I hope you are able to find a good solution for those angular applications.

Regarding the issue you reproted, see related https://github.com/CanopyTax/single-spa-angular/issues/59.

This is known/expected behavior, as we brainstorm better solutions.

With single-spa, there is only one HTML file, instead of one per angular application. Which means that the `scripts` and `assets` in the angular.json don't have a perfect way to be injected into the HTML like they would if there were a separate HTML file for each.

Options for you:
1) Add deepstream and echarts into [the root html file](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/root-html-file/index.html) (preferred). Use a CDN like cdnjs or jsdelivr, which have both of those libraries.
2) Add `import 'echarts/dist/echarts.min.js'` (and similar for deepstream) into your main.single-spa.ts file. Which includes them into your javascript bundle instead of in the HTML file.
3) Use a [partial webpack config](https://github.com/CanopyTax/single-spa-angular#ng-build-options) and add `deepstream` and `echarts` as [webpack externals](https://github.com/CanopyTax/single-spa-angular#ng-build-options). Make the externals be loaded from the CDN and then import them with `import 'echarts'` and `import 'deepstream'`:
```js
// in your partial webpack config
{
  externals: {
    "deepstream": "https://jsdelivr.com/...",
    "echarts": "https://jsdelivr.com/..."
  }
}
```

I'm closing this since I think I've explained why this doesn't work and how it is known/expected behavior. If you have ideas for how the scripts/assets from angular.json would be loaded, feel free to reopen or propose a change to single-spa-angular.

**Closed by joeldenning** 2019-06-21 13:36 UTC

**Comment by nashvillenarayan** [comment] 2019-07-06 03:49
Thanks !
